"""Synchronous boundary for the offline deterministic API."""

from __future__ import annotations

import math
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

from costpilot.audit import MICRODOLLARS_PER_USD, SQLiteAuditStore
from costpilot.classifier import (
    load_dataset,
    predict_tier,
    train_classifier,
    train_test_split_dataset,
)
from costpilot.domain import ModelConfig, Request, Response
from costpilot.providers.fake import FAKE_MODELS, FakeProvider
from costpilot.reporting import OFFLINE_BANNER, build_report
from costpilot.routing import classify_and_route, load_routing_config
from costpilot.verification import (
    VerificationConfig,
    load_verification_config,
    rerun_with_reference,
    should_escalate,
    verify_response,
)

DATASET_STATUS = "ai_drafted_pending_human_review"


@dataclass(frozen=True)
class Completion:
    request_id: str
    output_text: str
    classifier_tier: str
    routed_response: Response
    verification_response: Response
    verification_score: float
    verification_threshold: float
    verification_passed: bool
    escalated: bool
    rerun_response: Response | None


class _RecordingFakeProvider(FakeProvider):
    """Captures deterministic responses already generated by Phase 3 calls."""

    def __init__(self) -> None:
        self.responses: list[Response] = []

    def send(self, request: Request, model: ModelConfig) -> Response:
        response = super().send(request, model)
        self.responses.append(response)
        return response


class OfflineService:
    """Load fixed local inputs once and execute one auditable fake lifecycle."""

    def __init__(
        self,
        *,
        dataset_path: Path,
        routing_config_path: Path,
        verification_config_path: Path,
        audit_database_path: Path,
    ) -> None:
        dataset = load_dataset(dataset_path)
        if dataset.status != DATASET_STATUS or not dataset.examples:
            raise ValueError("Classifier dataset has unsupported provenance or no examples")
        train_examples, _ = train_test_split_dataset(dataset)
        self._classifier = train_classifier(train_examples)
        self._routing_config = load_routing_config(routing_config_path)
        for tier in ("tier_1", "tier_2", "tier_3"):
            model_id = self._routing_config.get(tier)
            if model_id not in FAKE_MODELS:
                raise ValueError("Routing configuration must map every tier to a canonical fake model")
        self._verification_config: VerificationConfig = load_verification_config(
            verification_config_path
        )
        self._store = SQLiteAuditStore(audit_database_path)

    def complete(
        self,
        prompt: str,
        request_id: str,
        verification_threshold: float | None = None,
        timestamp: datetime | None = None,
    ) -> Completion:
        threshold = self._verification_config.default_threshold
        if verification_threshold is not None:
            if not math.isfinite(verification_threshold) or not 0.0 <= verification_threshold <= 1.0:
                raise ValueError("Verification threshold must be between 0.0 and 1.0")
            threshold = verification_threshold

        request = Request(prompt=prompt, request_id=request_id)
        provider = _RecordingFakeProvider()
        classifier_tier = predict_tier(prompt, self._classifier)
        routed_model = classify_and_route(prompt, self._classifier, self._routing_config)
        routed_response = provider.send(request, routed_model)
        verification = verify_response(
            request,
            routed_response,
            self._verification_config.reference_model,
            provider,
            threshold,
        )
        verification_response = provider.responses[-1]
        rerun_response = (
            rerun_with_reference(request, self._verification_config.reference_model, provider)
            if should_escalate(verification)
            else None
        )
        self._store.append(
            datetime.now(UTC) if timestamp is None else timestamp,
            request,
            classifier_tier,
            routed_response,
            verification=verification,
            verification_response=verification_response,
            rerun_response=rerun_response,
        )
        final_response = rerun_response or routed_response
        return Completion(
            request_id=request_id,
            output_text=final_response.output_text,
            classifier_tier=classifier_tier,
            routed_response=routed_response,
            verification_response=verification_response,
            verification_score=verification.quality_score,
            verification_threshold=verification.threshold,
            verification_passed=verification.passed,
            escalated=rerun_response is not None,
            rerun_response=rerun_response,
        )

    def models(self) -> list[dict[str, object]]:
        return [
            {
                "provider": model.provider,
                "model_id": model.model_id,
                "quality_tier": model.quality_tier,
                "cost_per_input_token_microusd": round(
                    model.cost_per_input_token * MICRODOLLARS_PER_USD
                ),
                "cost_per_output_token_microusd": round(
                    model.cost_per_output_token * MICRODOLLARS_PER_USD
                ),
                "average_latency_ms": model.avg_latency_ms,
            }
            for model in FAKE_MODELS.values()
        ]

    def config(self) -> dict[str, object]:
        return {
            "routing": dict(self._routing_config),
            "verification": {
                "reference_model_id": self._verification_config.reference_model.model_id,
                "default_threshold": self._verification_config.default_threshold,
            },
            "dataset_status": DATASET_STATUS,
        }

    def stats(self) -> dict[str, object]:
        report = build_report(self._store)
        return {
            "event_count": report.event_count,
            "routed_cost_microusd": report.routed_cost_microusd,
            "lifecycle_cost_microusd": report.lifecycle_cost_microusd,
            "direct_gpt4o_cost_microusd": report.direct_gpt4o_cost_microusd,
            "routing_only_simulated_delta_microusd": report.routing_only_reduction_microusd,
            "end_to_end_simulated_delta_microusd": report.end_to_end_delta_microusd,
            "escalation_count": report.escalation_count,
            "verification_pass_rate": report.verification_pass_rate,
            "simulated_escalation_rate": report.escalation_rate,
            "routing_distribution": report.routing_distribution,
            "verification_distribution": report.verification_distribution,
        }

    @staticmethod
    def provenance() -> dict[str, object]:
        return {
            "offline_deterministic": True,
            "provider": "FakeProvider",
            "disclaimer": OFFLINE_BANNER,
            "dataset_status": DATASET_STATUS,
        }
